apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
spec: 
  type: LoadBalancer
  ports:
    - name: frontend
      port: 3000
    
    - name: backend
      port: 7777
  selector:
      app: load-balancer
